-- Generated by Mocodo 4.2.4

CREATE TABLE CARTE (
  PRIMARY KEY (code_carte),
  code_carte VARCHAR(42) NOT NULL,
  titre      VARCHAR(42),
  ordre      VARCHAR(42),
  couleur    VARCHAR(42),
  code_liste VARCHAR(42) NOT NULL
);

CREATE TABLE LABEL (
  PRIMARY KEY (code_label),
  code_label VARCHAR(42) NOT NULL,
  nom        VARCHAR(42),
  couleur    VARCHAR(42)
);

CREATE TABLE LISTE (
  PRIMARY KEY (code_liste),
  code_liste VARCHAR(42) NOT NULL,
  nom        VARCHAR(42),
  ordre      VARCHAR(42)
);

CREATE TABLE POSSEDE (
  PRIMARY KEY (code_label, code_carte),
  code_label VARCHAR(42) NOT NULL,
  code_carte VARCHAR(42) NOT NULL
);

ALTER TABLE CARTE ADD FOREIGN KEY (code_liste) REFERENCES LISTE (code_liste);

ALTER TABLE POSSEDE ADD FOREIGN KEY (code_carte) REFERENCES CARTE (code_carte);
ALTER TABLE POSSEDE ADD FOREIGN KEY (code_label) REFERENCES LABEL (code_label);
